### PR TITLE
Graphics starter code

### PR DESCRIPTION
**Pull request by chris1625**
Merging into master to include VS project changes, and a more up-to-date ancestor to make future merges a bit easier.

### CODE REVIEW

**Comment by WeichenLiu** [comment]
It's not quite finished yet. I messed up some project structures in Client project file. I fixed it in the new pull request, and added framebuffer class, which enable some sort of rendering onto the screen. 
After that pull request gets reviewed and merged into graphics branch, the graphics branch should be fine to go.

**Comment by chris1625** [comment]
> It's not quite finished yet. I messed up some project structures in Client project file. I fixed it in the new pull request, and added framebuffer class, which enable some sort of rendering onto the screen.
> After that pull request gets reviewed and merged into graphics branch, the graphics branch should be fine to go.

Ah damn, my bad. Just fixed the project XML myself, woops

**Comment by WeichenLiu** [comment]
I messed it up when manually merging project filters. :( I would prefer not to create another filter conflict.

**Comment by chris1625** [comment]
Have you pulled graphics yet? If you haven't I can just go ahead and revert my changes

**Comment by WeichenLiu** [comment]
I am waiting for Andy review my pull request. Once it's merged, the graphics code can render thing through stages of framebuffer and can add any other render routines in between. 

And if you have time to look over my FBO codes in other pull request, feel free to merge it.

**Comment by chris1625** [comment]
Alright I reverted my change, sorry about the mess. Hopefully no one pulled during that time lol

**Pull request merged**
